### PR TITLE
[WIP] Documentation upgrades

### PR DESCRIPTION
**Pull request by p-flock**

### CODE REVIEW

**Comment by wyatt-howe** [comment]
The sidebar member links only work if you are already in that namespace.

**Comment by p-flock** [comment]
> The sidebar member links only work if you are already in that namespace.

I can't replicate this - seems to work for me. Are you loading files into the browser directly or serving them from a local server?

**Comment by wyatt-howe** [comment]
> > The sidebar member links only work if you are already in that namespace.
> 
> I can't replicate this - seems to work for me. Are you loading files into the browser directly or serving them from a local server?

[Directly](https://htmlpreview.github.io/?https://raw.githubusercontent.com/multiparty/jiff/PF_documentation_updates/docs/jsdoc/index.html).  The links must be generated after the page loads, and the html preview messes this up.

**Comment by p-flock** [comment]
Merged into merge-preprocessing, which will then be merged to master

**Pull request closed without merging**
